### ISSUE TITLE
callback for before leave starts

### ISSUE THREAD

**Issue by SeabassNg** [faceyspacey/transition-group#3]
Currently, the onLeave method is invoked after animation. Need one for before.

**Comment by faceyspacey** [comment]
PR it. It's not a huge package. If we do it tho then we need two callbacks for every kind of callback for consistency, as well as updated docs. If we have to rename existing callbacks to include before or after that's fine. We will just do a major version bump. Not many people know about this package.

**Comment by SeabassNg** [comment]
https://github.com/faceyspacey/transition-group/pull/4

**Comment by faceyspacey** [comment]
excellent job with the tests. it's published. good luck with your app!
